name: gdm_bloc
description: GDM app that showcases bloc state management patterns.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  drop_down_list: ^0.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  flutter_svg: ^1.0.3
  flutter_vector_icons: ^1.0.0
  formz: ^0.4.1
  google_fonts: ^2.3.2
  hive  : ^2.1.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  ngi_api:
    path: packages/ngi_api
  ngi_repository:
    path: packages/ngi_repository
  tuple: ^2.0.0


dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/fleet/building/
    - assets/images/fleet/bus/
    - assets/images/fleet/commercialVehicle/
    - assets/images/fleet/concreteMixer/
    - assets/images/fleet/container/
    - assets/images/fleet/containerTruck/
    - assets/images/fleet/dumpTruck/
    - assets/images/fleet/fuelTankTruck/
    - assets/images/fleet/guide/
    - assets/images/fleet/home/
    - assets/images/fleet/lightTruck/
    - assets/images/fleet/motorcycle/
    - assets/images/fleet/person/
    - assets/images/fleet/personalVehicle/
    - assets/images/fleet/pilgrim/
    - assets/images/fleet/refrigeratedTruck/
    - assets/images/fleet/refrigerator/
    - assets/images/fleet/shelter/
    - assets/images/fleet/ship/
    - assets/images/fleet/shop/
    - assets/images/fleet/speedboat/
    - assets/images/fleet/store/
    - assets/images/fleet/tank/
    - assets/images/fleet/tankTruck/
    - assets/images/fleet/trailerTruck/
    - assets/images/fleet/train/
    - assets/images/fleet/truck/
    - assets/images/fleet/utilityTruck/
    - assets/images/fleet/warehouse/
    - assets/images/user/
    - assets/images/login/
    - assets/images/sidebar/
    - assets/images/
