name: ngi_repository
description: A repository that handles asset related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  hive  : ^2.1.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  meta: ^1.7.0

  ngi_api:
    path: ../ngi_api
  socket_io_client: ^1.0.2
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  test: ^1.21.1
  very_good_analysis: ^2.4.0
