name: ngi_api
description: The interface and models for an API providing access to assets.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.4.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  test: ^1.21.1
  very_good_analysis: ^2.4.0
